# Site settings
title: Rebittance.org
email: hello@rebittance.org
baseurl: "/rebittance" # the subpath of your site, e.g. /blog/
url: "http://rebittance.org" # the base hostname & protocol for your site
twitter_username: rebitPH
github_username:  sciventures

# Build settings
markdown: kramdown
